name: venv

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - lazrs-python
  - laspy
  - pip
  - scipy
  - mock
  - plyfile
  - python-dateutil
  - shapely
  - pyshp
  - pandas
  - click
  - colorama
  - psutil
  - numpy
  - pip:
      - -r requirements.txt
      - .
